[package]
name = "candle-xtts"
version = "0.1.0"
edition = "2021"

[dependencies]
candle-core = "0.8.1"
candle-einops = "0.1.2"
candle-nn = "0.8.1"
candle-transformers = "0.8.1"
serde = "1.0.216"
serde_json = "1.0.133"
