[package]
name = "candle-xtts"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
candle-core = "0.8.2"
candle-nn = "0.8.2"
candle-transformers = "0.8.2"
libsoxr = "0.2.9"
serde = "1.0.217"
serde_json = "1.0.135"
wavers = "1.5.1"
